# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestScraping():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_scraping(self):
    self.driver.get("https://vincigit00-amazon-scraping-app-nfzu99.streamlit.app/")
    self.driver.set_window_size(1512, 945)
    self.driver.switch_to.frame(0)
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.CSS_SELECTOR, ".st-bz").click()
    self.driver.find_element(By.CSS_SELECTOR, ".st-bz").send_keys("https://www.amazon.it/s?k=headphones&__mk_it_IT=ÅMÅŽÕÑ&crid=126DOIA2C3IFA&sprefix=headphone%2Caps%2C177&ref=nb_sb_noss_2")
    self.driver.find_element(By.CSS_SELECTOR, ".st-bz").send_keys(Keys.ENTER)
    self.driver.find_element(By.CSS_SELECTOR, ".st-cw > .st-bu").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.CSS_SELECTOR, ".css-1sslkv8 > p").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.LINK_TEXT, "Download CSV").click()
  
